### ISSUE TITLE
Improving aspect extracting using structured knowledge bases

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#71]
The idea is to use WikiData or DBpedia to filter out candidate for aspects, which are used in the sentences. The aspect words extracted from text should also appear as aspects of these object in some knowledge base (or as aspects of hypernyms of these objects). This should remove a lot of noisy aspects.

**Comment by ChulioZ** [comment]
Here's a little update on the current status:

I've created the csv file with the tests of our example object pairings as requested. I have just pushed it so you can have a look at it.

Some explanations for the setup of the file:

- Columns A & B are the objects to compare.
- Columns C & D are the list of aspects I find for the objects via WikiData.
- Column E are the overlapping WikiData aspects for both objects.
- Column F is the number of WikiData aspect overlaps.
- Columns G & H are the aspects our current iteration of CAM (default) finds for both objects.
- Columns I to L are the overlaps between aspects found via WikiData and via CAM for both objects as well as their counts.

A few more explanations as to how the WikiData aspects are collected:

- My method currently asks for both objects as parameters and then searches WikiData for database entries for the first object and for the second object.
- As there are usually multiple results for each search (hundreds, thousands, ...) the method has to choose which one fits best. This is context dependant (at least the method assumes so): If you look for Python and Java you usually mean the programming languages; if you look for Python and Viper you usually mean the snakes instead (you can actually see this exact example within the csv file). To find the most fitting one the method checks two options: If there's an entry for the first object and an entry for the second object that both share an "instance of" statement, those entries are chosen. If there are no such entries instead the two entries that have the most statements in common are chosen.
- Currently only aspects directly from each object are included. Aspects of their superclasses aren't. This may very well be changed in the future.

A first look at the results shows that there are quite a few overlaps between both objects regarding their WikiData aspects. That means that most of the times the correct choice seems to have been made regarding which entry to use. On the other hand, in the potato/steak example not the food is chosen but two films instead as there happens to be a film with Potato in its name and another one with Steak in its name. This choice doesn't even change when the "instance of" criterion is dismissed because this one overlap is still the most of them all -- funnily enough, the WikiData entries for Potato and Steak (the food ones you would expect) don't have a single aspect in common! This is definitely something to improve in the future -- I'm open for ideas.

Regarding the overlaps between the WikiData aspects and our CAM aspects, there are not that many: 3 is the highest number while many objects even have 0 in common between WikiData and CAM.

For me, a question has raised regarding the aspects overall because there seem to be two types of aspects and I'm not sure which type we actually want to show in CAM:

1. Aspects that describe the object, for example gamecube -> Nintendo, java -> programming language.
2. Aspects that describe why an object won the comparison, for example java -> performance, potato -> taste.

Which type do we actually want? Because for the first type of aspects, WikiData seems to be pretty good. For the second type it seems to be horrendous though -- aspects that describe the result of a comparison depend on the second object and describe aspects in which one object is better than the other but they don't describe the object itself which is what WikiData does. So I'm actually pretty curious about your opinions on that topic.

If you have any other questions feel free to ask them!

**Comment by alexanderpanchenko** [comment]
Thanks - please upload to a google doc spreadsheet for convinience.

**Comment by ChulioZ** [comment]
I did, here's the link:

https://docs.google.com/spreadsheets/d/1k_hD8qM5IU82eMmIiSAe2FAlzaH81YDuVtSrz2WoBSk/edit?usp=sharing

**Comment by alexanderpanchenko** [comment]
please share link for edit

**Comment by ChulioZ** [comment]
Ah yes, here, I'm not that used to Google Docs:

https://docs.google.com/spreadsheets/d/1k_hD8qM5IU82eMmIiSAe2FAlzaH81YDuVtSrz2WoBSk/edit?usp=sharing

**Comment by alexanderpanchenko** [comment]
currently you retrieve only the first hit, e.g. ‘milk’ corresponds to a film by Gas Van Sent. 

It would be great to generate the same table, but with 5 top hits per word (you can keep this table as is, just add one extra sheet).

**Comment by ChulioZ** [comment]
I'm actually not only retrieving the first hit. I currently take the top 10 hits and then choose the hit that fits best (depending on the top 10 hits from the second word).

Shall I include an extra sheet with top 5(/10) hits combined without choosing a specific option? I could also add a third sheet with taking the first hit always if you want that. I just thought that that wouldn't make that much sense -- take Python as an example ...

**Comment by ChulioZ** [comment]
I've now added two additional sheets:

The first sheet still shows the results when choosing the best fitting hits out of the top 10 hits.

The second sheet shows the results when choosing the first hit only.

The third sheet shows the results when choosing the top 10 hits combined.

**Comment by ChulioZ** [comment]
Closing because WikiData doesn't seem to fit our needs for now.
